# Generated by Django 3.2.5 on 2022-01-04 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.CharField(max_length=20)),
                ('no_of_beds', models.CharField(max_length=20)),
                ('living_student', models.IntegerField(default=0)),
                ('active', models.BooleanField()),
            ],
        ),
    ]
