# Generated by Django 3.2.5 on 2022-01-06 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=30)),
                ('father_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('student_cnic', models.CharField(max_length=30)),
                ('college_name', models.CharField(max_length=100)),
                ('phone_no', models.CharField(max_length=30)),
                ('room_no', models.CharField(max_length=10)),
            ],
        ),
    ]
