# Generated by Django 3.2.5 on 2022-01-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_studentsfee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=20)),
            ],
        ),
    ]
