# Generated by Django 3.2.5 on 2022-01-12 17:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='date',
            field=models.CharField(default=datetime.datetime, max_length=20),
        ),
    ]
