# Generated by Django 3.2.5 on 2022-01-12 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_expense_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='date',
            new_name='time',
        ),
    ]
