# Generated by Django 3.2.5 on 2022-01-12 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_date_expense_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='time',
        ),
    ]
