# Generated by Django 3.2.5 on 2022-01-12 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_expense_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='date',
            field=models.CharField(default=False, max_length=20),
        ),
    ]
