# Generated by Django 3.2.5 on 2022-01-15 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_expense_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeName', models.CharField(max_length=30)),
                ('phoneNo', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('cnic', models.CharField(max_length=30)),
                ('designation', models.CharField(max_length=30)),
            ],
        ),
    ]
